lb:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
app1:
  image: app
  links:
    - redis
  environment:
    VIRTUAL_HOST: 192.168.59.103
app2:
  image: app
  links:
    - redis
  environment:
    VIRTUAL_HOST: 192.168.59.103
redis:
  image: redis
  ports:
    - "6000:6379"